// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __toplevel_r_V_H__
#define __toplevel_r_V_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct toplevel_r_V_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 5;
  static const unsigned AddressRange = 64;
  static const unsigned AddressWidth = 6;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(toplevel_r_V_ram) {
        ram[0] = "0b00111";
        ram[1] = "0b01100";
        ram[2] = "0b10001";
        ram[3] = "0b10110";
        ram[4] = "0b00111";
        ram[5] = "0b01100";
        ram[6] = "0b10001";
        ram[7] = "0b10110";
        ram[8] = "0b00111";
        ram[9] = "0b01100";
        ram[10] = "0b10001";
        ram[11] = "0b10110";
        ram[12] = "0b00111";
        ram[13] = "0b01100";
        ram[14] = "0b10001";
        ram[15] = "0b10110";
        ram[16] = "0b00101";
        ram[17] = "0b01001";
        ram[18] = "0b01110";
        ram[19] = "0b10100";
        ram[20] = "0b00101";
        ram[21] = "0b01001";
        ram[22] = "0b01110";
        ram[23] = "0b10100";
        ram[24] = "0b00101";
        ram[25] = "0b01001";
        ram[26] = "0b01110";
        ram[27] = "0b10100";
        ram[28] = "0b00101";
        ram[29] = "0b01001";
        ram[30] = "0b01110";
        ram[31] = "0b10100";
        ram[32] = "0b00100";
        ram[33] = "0b01011";
        ram[34] = "0b10000";
        ram[35] = "0b10111";
        ram[36] = "0b00100";
        ram[37] = "0b01011";
        ram[38] = "0b10000";
        ram[39] = "0b10111";
        ram[40] = "0b00100";
        ram[41] = "0b01011";
        ram[42] = "0b10000";
        ram[43] = "0b10111";
        ram[44] = "0b00100";
        ram[45] = "0b01011";
        ram[46] = "0b10000";
        ram[47] = "0b10111";
        ram[48] = "0b00110";
        ram[49] = "0b01010";
        ram[50] = "0b01111";
        ram[51] = "0b10101";
        ram[52] = "0b00110";
        ram[53] = "0b01010";
        ram[54] = "0b01111";
        ram[55] = "0b10101";
        ram[56] = "0b00110";
        ram[57] = "0b01010";
        ram[58] = "0b01111";
        ram[59] = "0b10101";
        ram[60] = "0b00110";
        ram[61] = "0b01010";
        ram[62] = "0b01111";
        ram[63] = "0b10101";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(toplevel_r_V) {


static const unsigned DataWidth = 5;
static const unsigned AddressRange = 64;
static const unsigned AddressWidth = 6;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


toplevel_r_V_ram* meminst;


SC_CTOR(toplevel_r_V) {
meminst = new toplevel_r_V_ram("toplevel_r_V_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~toplevel_r_V() {
    delete meminst;
}


};//endmodule
#endif
