#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/usr/userfs/a/az579/Workspace/EMBS/FPGA/P6/P6.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /opt/york/cs/net/xilinx_vivado-2015.4_ise-14.7_x86-64-1/14.7/ISE_DS/EDK

SYSTEM = P6

MHSFILE = P6.mhs

FPGA_ARCH = spartan3e

DEVICE = xc3s500efg320-4

INTSTYLE = default

XPS_HDL_LANG = vhdl
GLOBAL_SEARCHPATHOPT = 
PROJECT_SEARCHPATHOPT =  -lp divcore/divcore/solution1/

SEARCHPATHOPT = $(PROJECT_SEARCHPATHOPT) $(GLOBAL_SEARCHPATHOPT)

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst

OBSERVE_PAR_OPTIONS = -error yes

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
MICROBLAZE_BOOTLOOP_LE = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop_le.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

MICROBLAZE_0_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_0.elf

BRAMINIT_ELF_IMP_FILES = $(MICROBLAZE_0_BOOTLOOP)
BRAMINIT_ELF_IMP_FILE_ARGS = -pe microblaze_0 $(MICROBLAZE_0_BOOTLOOP)

BRAMINIT_ELF_SIM_FILES = $(MICROBLAZE_0_BOOTLOOP)
BRAMINIT_ELF_SIM_FILE_ARGS = -pe microblaze_0 $(MICROBLAZE_0_BOOTLOOP)

SIM_CMD = xterm -e ./isim_P6

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.tcl

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.tcl

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.tcl

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_SIM_FILE_ARGS) -msg __xps/ise/xmsgprops.lst -s isim


CORE_STATE_DEVELOPMENT_FILES = divcore/divcore/solution1/impl/pcores/toplevel_top_v1_00_a/synhdl/verilog/toplevel_udiv_32ns_32ns_32_36.v \
divcore/divcore/solution1/impl/pcores/toplevel_top_v1_00_a/synhdl/verilog/toplevel.v \
divcore/divcore/solution1/impl/pcores/toplevel_top_v1_00_a/synhdl/verilog/toplevel_ap_rst_if.v \
divcore/divcore/solution1/impl/pcores/toplevel_top_v1_00_a/synhdl/verilog/toplevel_input_V_V_if.v \
divcore/divcore/solution1/impl/pcores/toplevel_top_v1_00_a/synhdl/verilog/toplevel_output_V_V_if.v \
divcore/divcore/solution1/impl/pcores/toplevel_top_v1_00_a/synhdl/verilog/toplevel_top.v

WRAPPER_NGC_FILES = implementation/P6_microblaze_0_wrapper.ngc \
implementation/P6_mb_plb_wrapper.ngc \
implementation/P6_ilmb_wrapper.ngc \
implementation/P6_dlmb_wrapper.ngc \
implementation/P6_dlmb_cntlr_wrapper.ngc \
implementation/P6_ilmb_cntlr_wrapper.ngc \
implementation/P6_lmb_bram_wrapper.ngc \
implementation/P6_rs232_dte_wrapper.ngc \
implementation/P6_leds_8bit_wrapper.ngc \
implementation/P6_dip_switches_4bit_wrapper.ngc \
implementation/P6_buttons_4bit_wrapper.ngc \
implementation/P6_ddr_sdram_wrapper.ngc \
implementation/P6_xps_timer_0_wrapper.ngc \
implementation/P6_clock_generator_0_wrapper.ngc \
implementation/P6_mdm_0_wrapper.ngc \
implementation/P6_proc_sys_reset_0_wrapper.ngc \
implementation/P6_toplevel_top_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/P6.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

SDK_EXPORT_DIR = SDK/SDK_Export/hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_BMM = $(SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
SYSTEM_HW_HANDOFF_DEP = $(SYSTEM_HW_HANDOFF) $(SYSTEM_HW_HANDOFF_BIT) $(SYSTEM_HW_HANDOFF_BMM)
