// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="toplevel,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc3s500efg320-4,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=16.157000,HLS_SYN_LAT=33071,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1236,HLS_SYN_LUT=2825}" *)

module toplevel (
        ap_clk,
        ap_rst,
        input_V_V_dout,
        input_V_V_empty_n,
        input_V_V_read,
        output_V_V_din,
        output_V_V_full_n,
        output_V_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 23'b1;
parameter    ap_ST_st2_fsm_1 = 23'b10;
parameter    ap_ST_st3_fsm_2 = 23'b100;
parameter    ap_ST_st4_fsm_3 = 23'b1000;
parameter    ap_ST_st5_fsm_4 = 23'b10000;
parameter    ap_ST_st6_fsm_5 = 23'b100000;
parameter    ap_ST_st7_fsm_6 = 23'b1000000;
parameter    ap_ST_st8_fsm_7 = 23'b10000000;
parameter    ap_ST_st9_fsm_8 = 23'b100000000;
parameter    ap_ST_st10_fsm_9 = 23'b1000000000;
parameter    ap_ST_st11_fsm_10 = 23'b10000000000;
parameter    ap_ST_st12_fsm_11 = 23'b100000000000;
parameter    ap_ST_st13_fsm_12 = 23'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 23'b10000000000000;
parameter    ap_ST_st15_fsm_14 = 23'b100000000000000;
parameter    ap_ST_st16_fsm_15 = 23'b1000000000000000;
parameter    ap_ST_st17_fsm_16 = 23'b10000000000000000;
parameter    ap_ST_st18_fsm_17 = 23'b100000000000000000;
parameter    ap_ST_st19_fsm_18 = 23'b1000000000000000000;
parameter    ap_ST_st20_fsm_19 = 23'b10000000000000000000;
parameter    ap_ST_st21_fsm_20 = 23'b100000000000000000000;
parameter    ap_ST_st22_fsm_21 = 23'b1000000000000000000000;
parameter    ap_ST_st23_fsm_22 = 23'b10000000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_12 = 32'b10010;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_10325476 = 32'b10000001100100101010001110110;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_98BADCFE = 32'b10011000101110101101110011111110;
parameter    ap_const_lv32_EFCDAB89 = 32'b11101111110011011010101110001001;
parameter    ap_const_lv32_67452301 = 32'b1100111010001010010001100000001;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_14 = 32'b10100;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_16 = 32'b10110;
parameter    ap_const_lv32_80 = 32'b10000000;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_FFFFFFFF = 32'b11111111111111111111111111111111;
parameter    ap_const_lv5_10 = 5'b10000;
parameter    ap_const_lv5_1 = 5'b1;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv6_38 = 6'b111000;
parameter    ap_const_lv6_37 = 6'b110111;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv33_1 = 33'b1;
parameter    ap_const_lv32_1C = 32'b11100;
parameter    ap_const_lv32_1D = 32'b11101;
parameter    ap_const_lv33_2 = 33'b10;
parameter    ap_const_lv33_3 = 33'b11;
parameter    ap_const_lv7_40 = 7'b1000000;
parameter    ap_const_lv7_1 = 7'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv7_30 = 7'b110000;
parameter    ap_const_lv8_5 = 8'b101;
parameter    ap_const_lv7_2 = 7'b10;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_const_lv9_140 = 9'b101000000;
parameter    ap_const_lv32_40 = 32'b1000000;
parameter    ap_const_lv57_3 = 57'b11;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input  [31:0] input_V_V_dout;
input   input_V_V_empty_n;
output   input_V_V_read;
output  [31:0] output_V_V_din;
input   output_V_V_full_n;
output   output_V_V_write;

reg input_V_V_read;
reg[31:0] output_V_V_din;
reg output_V_V_write;
reg   [31:0] initial_length_V = 32'b00000000000000000000000000000000;
reg   [8:0] BLA_address0;
reg    BLA_ce0;
reg    BLA_we0;
reg   [31:0] BLA_d0;
wire   [31:0] BLA_q0;
reg   [8:0] BLA_address1;
reg    BLA_ce1;
reg    BLA_we1;
reg   [31:0] BLA_d1;
wire   [31:0] BLA_q1;
reg   [31:0] h0_V = 32'b00000000000000000000000000000000;
reg   [31:0] h1_V = 32'b00000000000000000000000000000000;
reg   [31:0] h2_V = 32'b00000000000000000000000000000000;
reg   [31:0] h3_V = 32'b00000000000000000000000000000000;
reg   [31:0] a_V = 32'b00000000000000000000000000000000;
reg   [31:0] b_V = 32'b00000000000000000000000000000000;
reg   [31:0] c_V = 32'b00000000000000000000000000000000;
reg   [31:0] d_V = 32'b00000000000000000000000000000000;
reg   [31:0] f_V = 32'b00000000000000000000000000000000;
wire   [4:0] i_1_fu_626_p2;
reg   [4:0] i_1_reg_1728;
(* fsm_encoding = "none" *) reg   [22:0] ap_CS_fsm = 23'b1;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_76;
wire   [0:0] exitcond1_fu_620_p2;
reg    ap_sig_bdd_84;
reg   [31:0] tmp_V_4_reg_1734;
wire   [7:0] tmp_11_fu_632_p1;
reg   [7:0] tmp_11_reg_1741;
wire   [31:0] grp_fu_571_p2;
wire   [0:0] icmp_fu_646_p2;
wire   [31:0] t_V_2_fu_716_p2;
reg   [31:0] t_V_2_reg_1755;
wire   [31:0] tmp_6_fu_722_p2;
reg   [31:0] tmp_6_reg_1764;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_110;
reg   [7:0] phitmp_reg_1780;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_119;
wire   [0:0] icmp2_fu_753_p2;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_130;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_bdd_138;
wire   [31:0] t_V_1_fu_791_p2;
reg    ap_sig_cseq_ST_st9_fsm_8;
reg    ap_sig_bdd_147;
wire   [31:0] t_V_3_fu_817_p2;
reg    ap_sig_cseq_ST_st10_fsm_9;
reg    ap_sig_bdd_156;
wire   [32:0] lhs_V_1_cast_fu_854_p1;
reg   [32:0] lhs_V_1_cast_reg_1814;
wire   [0:0] tmp_10_fu_823_p2;
reg   [7:0] phitmp148_i_reg_1820;
reg   [7:0] phitmp149_i_reg_1825;
reg   [2:0] tmp_30_reg_1830;
wire   [31:0] tmp_19_fu_941_p2;
reg   [31:0] tmp_19_reg_1835;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_bdd_176;
wire   [32:0] lhs_V_2_cast_fu_955_p1;
reg   [32:0] lhs_V_2_cast_reg_1840;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_bdd_185;
reg   [31:0] h0_V_load_reg_1849;
reg    ap_sig_cseq_ST_st15_fsm_14;
reg    ap_sig_bdd_194;
wire   [0:0] tmp_28_fu_989_p2;
reg    ap_sig_bdd_200;
reg   [31:0] h1_V_load_reg_1854;
reg   [31:0] h2_V_load_reg_1859;
reg   [31:0] h3_V_load_reg_1864;
wire   [6:0] i_V_fu_1097_p2;
reg   [6:0] i_V_reg_1872;
reg    ap_sig_cseq_ST_st16_fsm_15;
reg    ap_sig_bdd_218;
wire   [0:0] exitcond_fu_1091_p2;
wire   [31:0] tmp_49_fu_1363_p3;
reg   [31:0] tmp_49_reg_1891;
wire   [31:0] tmp_34_fu_1376_p2;
wire   [31:0] tmp_35_fu_1387_p2;
wire   [31:0] tmp_36_fu_1398_p2;
wire   [31:0] tmp_37_fu_1409_p2;
wire   [31:0] tmp_38_fu_1420_p2;
reg   [31:0] BLA_load_reg_1926;
reg    ap_sig_cseq_ST_st17_fsm_16;
reg    ap_sig_bdd_247;
wire   [7:0] tmp_65_fu_1426_p1;
reg   [7:0] tmp_65_reg_1931;
wire   [32:0] lhs_V_14_cast_fu_1430_p1;
reg   [32:0] lhs_V_14_cast_reg_1936;
wire   [7:0] tmp_66_fu_1455_p1;
reg   [7:0] tmp_66_reg_1951;
reg    ap_sig_cseq_ST_st18_fsm_17;
reg    ap_sig_bdd_264;
wire   [7:0] tmp_67_fu_1459_p1;
reg   [7:0] tmp_67_reg_1956;
wire   [31:0] this_assign_1_fu_1510_p2;
reg   [31:0] this_assign_1_reg_1971;
reg    ap_sig_cseq_ST_st19_fsm_18;
reg    ap_sig_bdd_279;
wire   [4:0] tmp_69_fu_1516_p1;
reg   [4:0] tmp_69_reg_1977;
wire   [4:0] r_V_30_fu_1520_p2;
reg   [4:0] r_V_30_reg_1982;
reg   [31:0] initial_length_V_load_reg_395;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_291;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_bdd_299;
wire   [0:0] tmp_29_fu_777_p2;
reg   [4:0] i_reg_409;
reg   [31:0] initial_length_V_load6_reg_422;
reg   [31:0] initial_length_V_load5_reg_433;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_321;
wire   [0:0] icmp1_fu_728_p2;
reg   [31:0] initial_length_V_load4_reg_444;
reg   [31:0] storemerge_in_reg_456;
wire   [0:0] exitcond2_fu_801_p2;
reg   [31:0] storemerge1179_in_reg_466;
reg   [31:0] lhs_V_4_reg_476;
reg    ap_sig_cseq_ST_st14_fsm_13;
reg    ap_sig_bdd_349;
reg   [31:0] lhs_V_3_reg_488;
reg   [31:0] lhs_V_2_reg_500;
reg   [31:0] lhs_V_1_reg_512;
reg   [31:0] storemerge_reg_523;
reg   [6:0] t_V_6_reg_535;
reg    ap_sig_cseq_ST_st20_fsm_19;
reg    ap_sig_bdd_370;
wire   [8:0] tmp_47_cast_fu_1283_p1;
reg   [8:0] storemerge1182_in_phi_fu_550_p6;
wire   [0:0] icmp3_fu_1113_p2;
wire   [0:0] icmp4_fu_1129_p2;
wire   [8:0] tmp_46_fu_1175_p2;
wire   [0:0] tmp_43_fu_1135_p2;
wire   [8:0] tmp_51_cast_fu_1224_p1;
wire   [3:0] r_V_15_fu_1288_p1;
reg   [3:0] storemerge2_phi_fu_561_p4;
wire   [3:0] tmp_58_fu_1323_p1;
wire   [63:0] tmp_2_fu_652_p1;
wire   [63:0] tmp_8_fu_734_p1;
wire   [63:0] tmp_25_fu_768_p1;
wire   [63:0] tmp_32_fu_782_p1;
wire   [63:0] tmp_7_fu_812_p1;
wire   [63:0] tmp_13_fu_828_p1;
wire   [63:0] tmp_14_fu_833_p1;
wire   [63:0] tmp_15_fu_863_p1;
wire   [63:0] tmp_17_fu_918_p1;
reg    ap_sig_cseq_ST_st11_fsm_10;
reg    ap_sig_bdd_425;
wire   [63:0] tmp_18_fu_932_p1;
wire   [63:0] tmp_21_fu_946_p1;
wire   [63:0] tmp_22_fu_964_p1;
wire   [63:0] tmp_23_fu_974_p1;
wire   [63:0] tmp_24_fu_984_p1;
wire   [63:0] addr_cast_fu_1348_p1;
wire   [63:0] tmp_50_fu_1371_p1;
wire   [63:0] tmp_51_fu_1439_p1;
wire   [63:0] tmp_52_fu_1450_p1;
wire   [63:0] tmp_53_fu_1468_p1;
wire   [63:0] addr1_fu_1473_p3;
reg    ap_sig_cseq_ST_st21_fsm_20;
reg    ap_sig_bdd_451;
reg    ap_sig_cseq_ST_st22_fsm_21;
reg    ap_sig_bdd_461;
reg    ap_sig_cseq_ST_st23_fsm_22;
reg    ap_sig_bdd_470;
wire   [31:0] tmp_V_fu_1074_p5;
wire   [31:0] tmp_V_1_fu_1618_p5;
wire   [31:0] tmp_V_2_fu_1665_p5;
wire   [31:0] tmp_V_3_fu_1712_p5;
wire   [31:0] tmp_54_fu_1566_p2;
wire   [31:0] r_V_14_fu_1147_p2;
wire   [31:0] r_V_12_fu_1188_p2;
wire   [31:0] r_V_11_fu_1241_p2;
wire   [31:0] r_V_8_fu_1311_p2;
wire   [31:0] phitmp1_trunc_fu_667_p1;
wire   [31:0] phitmp2_trunc_fu_739_p1;
wire   [31:0] phitmp_trunc_fu_773_p1;
wire   [31:0] rhs_V_13_cast8_trunc_fu_787_p1;
wire   [31:0] p_0107_0_i1_trunc_fu_849_p1;
wire   [31:0] phitmp149_i_trunc_fu_937_p1;
wire   [31:0] phitmp_i_trunc_fu_878_p1;
wire   [31:0] phitmp148_i_trunc_fu_923_p1;
wire   [31:0] p_0107_0_i_trunc_fu_951_p1;
wire   [7:0] tmp_16_fu_636_p4;
wire   [7:0] phitmp1_fu_657_p4;
wire   [31:0] tmp_1_fu_696_p2;
wire   [5:0] tmp_fu_702_p1;
wire   [5:0] tmp_9_fu_706_p2;
wire   [31:0] tmp_3_fu_712_p1;
wire   [7:0] grp_fu_583_p4;
wire   [7:0] tmp_40_fu_744_p4;
wire   [5:0] tmp_20_fu_797_p1;
wire   [4:0] tmp_39_fu_837_p1;
wire   [7:0] p_0107_0_i1_fu_841_p3;
wire   [32:0] r_V_fu_857_p2;
wire   [7:0] phitmp_i_fu_868_p4;
wire   [32:0] r_V_1_fu_913_p2;
wire   [32:0] r_V_2_fu_927_p2;
wire   [32:0] r_V_3_fu_958_p2;
wire   [32:0] r_V_4_fu_969_p2;
wire   [32:0] r_V_5_fu_979_p2;
wire   [7:0] tmp_41_fu_1040_p1;
wire   [7:0] p_1_fu_1054_p4;
wire   [7:0] p_2_fu_1064_p4;
wire   [7:0] p_3_fu_1044_p4;
wire   [2:0] tmp_57_fu_1103_p4;
wire   [1:0] tmp_59_fu_1119_p4;
wire   [31:0] grp_fu_596_p2;
wire   [31:0] r_V_28_fu_1141_p2;
wire   [5:0] tmp_63_fu_1163_p1;
wire   [8:0] p_shl2_fu_1167_p3;
wire   [8:0] tmp_52_cast_fu_1159_p1;
wire   [31:0] tmp2_fu_1182_p2;
wire   [5:0] tmp_62_fu_1200_p1;
wire   [7:0] p_shl1_fu_1204_p3;
wire   [7:0] t_V_6_cast_fu_1087_p1;
wire   [7:0] tmp_44_fu_1212_p2;
wire   [7:0] tmp_45_fu_1218_p2;
wire   [31:0] r_V_27_fu_1235_p2;
wire   [31:0] r_V_26_fu_1229_p2;
wire   [6:0] tmp_61_fu_1257_p2;
wire   [5:0] tmp_60_fu_1253_p1;
wire   [5:0] tmp1_fu_1267_p2;
wire   [7:0] tmp1_cast_fu_1273_p1;
wire   [7:0] p_shl_cast_fu_1263_p1;
wire   [7:0] tmp_42_fu_1277_p2;
wire   [31:0] lhs_V_6_fu_1299_p2;
wire   [31:0] r_V_25_fu_1305_p2;
wire   [31:0] r_V_24_fu_1293_p2;
wire   [8:0] tmp_47_cast1_fu_1338_p1;
wire   [8:0] addr_fu_1342_p2;
wire   [27:0] tmp_48_fu_1353_p4;
wire   [32:0] r_V_16_fu_1433_p2;
wire   [32:0] r_V_17_fu_1444_p2;
wire   [32:0] r_V_18_fu_1463_p2;
wire   [7:0] tmp_68_fu_1486_p1;
wire   [31:0] r_V_19_fu_1490_p5;
wire   [31:0] tmp5_fu_1504_p2;
wire   [31:0] tmp4_fu_1499_p2;
wire   [31:0] this_assign_2_fu_1544_p1;
wire   [31:0] tmp_40_i_cast_fu_1552_p1;
wire   [31:0] r_V_31_fu_1555_p2;
wire   [31:0] r_V_29_fu_1547_p2;
wire   [31:0] r_V_23_fu_1560_p2;
wire   [7:0] tmp_47_fu_1584_p1;
wire   [7:0] p_5_fu_1598_p4;
wire   [7:0] p_6_fu_1608_p4;
wire   [7:0] p_4_fu_1588_p4;
wire   [7:0] tmp_55_fu_1631_p1;
wire   [7:0] p_9_fu_1645_p4;
wire   [7:0] p_s_fu_1655_p4;
wire   [7:0] p_8_fu_1635_p4;
wire   [7:0] tmp_56_fu_1678_p1;
wire   [7:0] p_10_fu_1692_p4;
wire   [7:0] p_11_fu_1702_p4;
wire   [7:0] p_7_fu_1682_p4;
reg   [22:0] ap_NS_fsm;
reg    ap_sig_bdd_1220;
reg    ap_sig_bdd_1222;
reg    ap_sig_bdd_1224;
reg    ap_sig_bdd_225;
reg    ap_sig_bdd_90;
reg    ap_sig_bdd_1229;
reg    ap_sig_bdd_1231;
reg    ap_sig_bdd_397;


toplevel_BLA #(
    .DataWidth( 32 ),
    .AddressRange( 448 ),
    .AddressWidth( 9 ))
BLA_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( BLA_address0 ),
    .ce0( BLA_ce0 ),
    .we0( BLA_we0 ),
    .d0( BLA_d0 ),
    .q0( BLA_q0 ),
    .address1( BLA_address1 ),
    .ce1( BLA_ce1 ),
    .we1( BLA_we1 ),
    .d1( BLA_d1 ),
    .q1( BLA_q1 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        a_V <= d_V;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & ~ap_sig_bdd_200 & ~(ap_const_lv1_0 == tmp_28_fu_989_p2))) begin
        a_V <= h0_V;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        b_V <= tmp_54_fu_1566_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & ~ap_sig_bdd_200 & ~(ap_const_lv1_0 == tmp_28_fu_989_p2))) begin
        b_V <= h1_V;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        c_V <= b_V;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & ~ap_sig_bdd_200 & ~(ap_const_lv1_0 == tmp_28_fu_989_p2))) begin
        c_V <= h2_V;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        d_V <= c_V;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & ~ap_sig_bdd_200 & ~(ap_const_lv1_0 == tmp_28_fu_989_p2))) begin
        d_V <= h3_V;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_bdd_225) begin
        if (~(ap_const_lv1_0 == icmp3_fu_1113_p2)) begin
            f_V <= r_V_8_fu_1311_p2;
        end else if (ap_sig_bdd_1224) begin
            f_V <= r_V_11_fu_1241_p2;
        end else if (ap_sig_bdd_1222) begin
            f_V <= r_V_12_fu_1188_p2;
        end else if (ap_sig_bdd_1220) begin
            f_V <= r_V_14_fu_1147_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~(ap_const_lv1_0 == exitcond_fu_1091_p2))) begin
        h0_V <= tmp_34_fu_1376_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~ap_sig_bdd_84 & ~(exitcond1_fu_620_p2 == ap_const_lv1_0))) begin
        h0_V <= ap_const_lv32_67452301;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~(ap_const_lv1_0 == exitcond_fu_1091_p2))) begin
        h1_V <= tmp_35_fu_1387_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~ap_sig_bdd_84 & ~(exitcond1_fu_620_p2 == ap_const_lv1_0))) begin
        h1_V <= ap_const_lv32_EFCDAB89;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~(ap_const_lv1_0 == exitcond_fu_1091_p2))) begin
        h2_V <= tmp_36_fu_1398_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~ap_sig_bdd_84 & ~(exitcond1_fu_620_p2 == ap_const_lv1_0))) begin
        h2_V <= ap_const_lv32_98BADCFE;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~(ap_const_lv1_0 == exitcond_fu_1091_p2))) begin
        h3_V <= tmp_37_fu_1409_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~ap_sig_bdd_84 & ~(exitcond1_fu_620_p2 == ap_const_lv1_0))) begin
        h3_V <= ap_const_lv32_10325476;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(ap_const_lv1_0 == tmp_29_fu_777_p2)))) begin
        i_reg_409 <= i_1_reg_1728;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) begin
        i_reg_409 <= ap_const_lv5_0;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_620_p2 == ap_const_lv1_0) & ~ap_sig_bdd_84 & (ap_const_lv1_0 == icmp_fu_646_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) | (ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7))) begin
        initial_length_V <= grp_fu_571_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) begin
        initial_length_V <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_lv1_0 == icmp2_fu_753_p2))) begin
        initial_length_V_load4_reg_444 <= initial_length_V_load5_reg_433;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        initial_length_V_load4_reg_444 <= grp_fu_571_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(ap_const_lv1_0 == icmp1_fu_728_p2))) begin
        initial_length_V_load5_reg_433 <= initial_length_V_load6_reg_422;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        initial_length_V_load5_reg_433 <= grp_fu_571_p2;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_bdd_90) begin
        if (~(ap_const_lv1_0 == icmp_fu_646_p2)) begin
            initial_length_V_load6_reg_422 <= initial_length_V_load_reg_395;
        end else if ((ap_const_lv1_0 == icmp_fu_646_p2)) begin
            initial_length_V_load6_reg_422 <= grp_fu_571_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_6) & ~(ap_const_lv1_0 == tmp_29_fu_777_p2))) begin
        initial_length_V_load_reg_395 <= initial_length_V_load4_reg_444;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        initial_length_V_load_reg_395 <= grp_fu_571_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) begin
        initial_length_V_load_reg_395 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~(ap_const_lv1_0 == exitcond_fu_1091_p2))) begin
        lhs_V_1_reg_512 <= tmp_34_fu_1376_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        lhs_V_1_reg_512 <= ap_const_lv32_67452301;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~(ap_const_lv1_0 == exitcond_fu_1091_p2))) begin
        lhs_V_2_reg_500 <= tmp_35_fu_1387_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        lhs_V_2_reg_500 <= ap_const_lv32_EFCDAB89;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~(ap_const_lv1_0 == exitcond_fu_1091_p2))) begin
        lhs_V_3_reg_488 <= tmp_36_fu_1398_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        lhs_V_3_reg_488 <= ap_const_lv32_98BADCFE;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~(ap_const_lv1_0 == exitcond_fu_1091_p2))) begin
        lhs_V_4_reg_476 <= tmp_37_fu_1409_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        lhs_V_4_reg_476 <= ap_const_lv32_10325476;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & ~(ap_const_lv1_0 == tmp_10_fu_823_p2))) begin
        storemerge1179_in_reg_466 <= t_V_3_fu_817_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~(ap_const_lv1_0 == exitcond2_fu_801_p2))) begin
        storemerge1179_in_reg_466 <= initial_length_V_load_reg_395;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & (ap_const_lv1_0 == exitcond2_fu_801_p2))) begin
        storemerge_in_reg_456 <= t_V_1_fu_791_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~ap_sig_bdd_84 & ~(exitcond1_fu_620_p2 == ap_const_lv1_0))) begin
        storemerge_in_reg_456 <= initial_length_V_load_reg_395;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~(ap_const_lv1_0 == exitcond_fu_1091_p2))) begin
        storemerge_reg_523 <= tmp_38_fu_1420_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        storemerge_reg_523 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st20_fsm_19)) begin
        t_V_6_reg_535 <= i_V_reg_1872;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & ~ap_sig_bdd_200 & ~(ap_const_lv1_0 == tmp_28_fu_989_p2))) begin
        t_V_6_reg_535 <= ap_const_lv7_0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        BLA_load_reg_1926 <= BLA_q1;
        lhs_V_14_cast_reg_1936[31 : 0] <= lhs_V_14_cast_fu_1430_p1[31 : 0];
        tmp_65_reg_1931 <= tmp_65_fu_1426_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & ~ap_sig_bdd_200 & ~(ap_const_lv1_0 == tmp_28_fu_989_p2))) begin
        h0_V_load_reg_1849 <= h0_V;
        h1_V_load_reg_1854 <= h1_V;
        h2_V_load_reg_1859 <= h2_V;
        h3_V_load_reg_1864 <= h3_V;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~ap_sig_bdd_84)) begin
        i_1_reg_1728 <= i_1_fu_626_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15)) begin
        i_V_reg_1872 <= i_V_fu_1097_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & (ap_const_lv1_0 == tmp_10_fu_823_p2))) begin
        lhs_V_1_cast_reg_1814[31 : 0] <= lhs_V_1_cast_fu_854_p1[31 : 0];
        phitmp148_i_reg_1820 <= {{initial_length_V_load_reg_395[ap_const_lv32_14 : ap_const_lv32_D]}};
        phitmp149_i_reg_1825 <= {{initial_length_V_load_reg_395[ap_const_lv32_1C : ap_const_lv32_15]}};
        tmp_30_reg_1830 <= {{initial_length_V_load_reg_395[ap_const_lv32_1F : ap_const_lv32_1D]}};
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        lhs_V_2_cast_reg_1840[31 : 0] <= lhs_V_2_cast_fu_955_p1[31 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & (ap_const_lv1_0 == icmp2_fu_753_p2))) begin
        phitmp_reg_1780 <= {{tmp_V_4_reg_1734[ap_const_lv32_F : ap_const_lv32_8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st19_fsm_18)) begin
        r_V_30_reg_1982 <= r_V_30_fu_1520_p2;
        this_assign_1_reg_1971 <= this_assign_1_fu_1510_p2;
        tmp_69_reg_1977 <= tmp_69_fu_1516_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~ap_sig_bdd_84 & ~(exitcond1_fu_620_p2 == ap_const_lv1_0))) begin
        t_V_2_reg_1755 <= t_V_2_fu_716_p2;
        tmp_6_reg_1764 <= tmp_6_fu_722_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_620_p2 == ap_const_lv1_0) & ~ap_sig_bdd_84)) begin
        tmp_11_reg_1741 <= tmp_11_fu_632_p1;
        tmp_V_4_reg_1734 <= input_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        tmp_19_reg_1835 <= tmp_19_fu_941_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == exitcond_fu_1091_p2))) begin
        tmp_49_reg_1891 <= tmp_49_fu_1363_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17)) begin
        tmp_66_reg_1951 <= tmp_66_fu_1455_p1;
        tmp_67_reg_1956 <= tmp_67_fu_1459_p1;
    end
end

always @ (ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st10_fsm_9 or tmp_10_fu_823_p2 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st17_fsm_16 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st14_fsm_13 or tmp_2_fu_652_p1 or tmp_8_fu_734_p1 or tmp_25_fu_768_p1 or tmp_32_fu_782_p1 or tmp_7_fu_812_p1 or tmp_13_fu_828_p1 or tmp_14_fu_833_p1 or ap_sig_cseq_ST_st11_fsm_10 or tmp_18_fu_932_p1 or tmp_24_fu_984_p1 or tmp_50_fu_1371_p1 or tmp_52_fu_1450_p1 or addr1_fu_1473_p3) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        BLA_address0 = tmp_24_fu_984_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        BLA_address0 = tmp_18_fu_932_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & (ap_const_lv1_0 == tmp_10_fu_823_p2))) begin
        BLA_address0 = tmp_14_fu_833_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & ~(ap_const_lv1_0 == tmp_10_fu_823_p2))) begin
        BLA_address0 = tmp_13_fu_828_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        BLA_address0 = tmp_7_fu_812_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        BLA_address0 = tmp_32_fu_782_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        BLA_address0 = tmp_25_fu_768_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        BLA_address0 = tmp_8_fu_734_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        BLA_address0 = tmp_2_fu_652_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17)) begin
        BLA_address0 = addr1_fu_1473_p3;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        BLA_address0 = tmp_52_fu_1450_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15)) begin
        BLA_address0 = tmp_50_fu_1371_p1;
    end else begin
        BLA_address0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st17_fsm_16 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st14_fsm_13 or tmp_15_fu_863_p1 or tmp_17_fu_918_p1 or ap_sig_cseq_ST_st11_fsm_10 or tmp_21_fu_946_p1 or tmp_22_fu_964_p1 or tmp_23_fu_974_p1 or addr_cast_fu_1348_p1 or tmp_51_fu_1439_p1 or tmp_53_fu_1468_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        BLA_address1 = tmp_23_fu_974_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        BLA_address1 = tmp_22_fu_964_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        BLA_address1 = tmp_21_fu_946_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        BLA_address1 = tmp_17_fu_918_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        BLA_address1 = tmp_15_fu_863_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17)) begin
        BLA_address1 = tmp_53_fu_1468_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16)) begin
        BLA_address1 = tmp_51_fu_1439_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15)) begin
        BLA_address1 = addr_cast_fu_1348_p1;
    end else begin
        BLA_address1 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st2_fsm_1 or ap_sig_bdd_84 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st10_fsm_9 or tmp_10_fu_823_p2 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st17_fsm_16 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st14_fsm_13 or ap_sig_cseq_ST_st11_fsm_10) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~ap_sig_bdd_84) | (ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) | (ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | (ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) | ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & (ap_const_lv1_0 == tmp_10_fu_823_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | (ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) | ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & ~(ap_const_lv1_0 == tmp_10_fu_823_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10))) begin
        BLA_ce0 = ap_const_logic_1;
    end else begin
        BLA_ce0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_cseq_ST_st17_fsm_16 or ap_sig_cseq_ST_st18_fsm_17 or ap_sig_cseq_ST_st14_fsm_13 or ap_sig_cseq_ST_st11_fsm_10) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) | (ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) | (ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) | (ap_const_logic_1 == ap_sig_cseq_ST_st17_fsm_16) | (ap_const_logic_1 == ap_sig_cseq_ST_st18_fsm_17) | (ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10))) begin
        BLA_ce1 = ap_const_logic_1;
    end else begin
        BLA_ce1 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st2_fsm_1 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st10_fsm_9 or tmp_10_fu_823_p2 or ap_sig_cseq_ST_st14_fsm_13 or ap_sig_cseq_ST_st11_fsm_10 or phitmp1_trunc_fu_667_p1 or phitmp2_trunc_fu_739_p1 or phitmp_trunc_fu_773_p1 or rhs_V_13_cast8_trunc_fu_787_p1 or p_0107_0_i1_trunc_fu_849_p1 or phitmp149_i_trunc_fu_937_p1) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        BLA_d0 = phitmp149_i_trunc_fu_937_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & (ap_const_lv1_0 == tmp_10_fu_823_p2))) begin
        BLA_d0 = p_0107_0_i1_trunc_fu_849_p1;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & ~(ap_const_lv1_0 == tmp_10_fu_823_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13))) begin
        BLA_d0 = ap_const_lv32_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8)) begin
        BLA_d0 = ap_const_lv32_80;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7)) begin
        BLA_d0 = rhs_V_13_cast8_trunc_fu_787_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        BLA_d0 = phitmp_trunc_fu_773_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        BLA_d0 = phitmp2_trunc_fu_739_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        BLA_d0 = phitmp1_trunc_fu_667_p1;
    end else begin
        BLA_d0 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st10_fsm_9 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st14_fsm_13 or ap_sig_cseq_ST_st11_fsm_10 or phitmp_i_trunc_fu_878_p1 or phitmp148_i_trunc_fu_923_p1 or p_0107_0_i_trunc_fu_951_p1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) | (ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13))) begin
        BLA_d1 = ap_const_lv32_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        BLA_d1 = p_0107_0_i_trunc_fu_951_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10)) begin
        BLA_d1 = phitmp148_i_trunc_fu_923_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9)) begin
        BLA_d1 = phitmp_i_trunc_fu_878_p1;
    end else begin
        BLA_d1 = 'bx;
    end
end

always @ (ap_sig_cseq_ST_st2_fsm_1 or exitcond1_fu_620_p2 or ap_sig_bdd_84 or icmp_fu_646_p2 or ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st6_fsm_5 or ap_sig_cseq_ST_st8_fsm_7 or ap_sig_cseq_ST_st9_fsm_8 or ap_sig_cseq_ST_st10_fsm_9 or tmp_10_fu_823_p2 or exitcond2_fu_801_p2 or ap_sig_cseq_ST_st14_fsm_13 or ap_sig_cseq_ST_st11_fsm_10) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_620_p2 == ap_const_lv1_0) & ~ap_sig_bdd_84 & (ap_const_lv1_0 == icmp_fu_646_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5) | (ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_7) | ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & (ap_const_lv1_0 == tmp_10_fu_823_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st9_fsm_8) & ~(ap_const_lv1_0 == exitcond2_fu_801_p2)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & ~(ap_const_lv1_0 == tmp_10_fu_823_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10))) begin
        BLA_we0 = ap_const_logic_1;
    end else begin
        BLA_we0 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st10_fsm_9 or tmp_10_fu_823_p2 or ap_sig_cseq_ST_st12_fsm_11 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st14_fsm_13 or ap_sig_cseq_ST_st11_fsm_10) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st10_fsm_9) & (ap_const_lv1_0 == tmp_10_fu_823_p2)) | (ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) | (ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10))) begin
        BLA_we1 = ap_const_logic_1;
    end else begin
        BLA_we1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_156) begin
    if (ap_sig_bdd_156) begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_425) begin
    if (ap_sig_bdd_425) begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_176) begin
    if (ap_sig_bdd_176) begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_185) begin
    if (ap_sig_bdd_185) begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_349) begin
    if (ap_sig_bdd_349) begin
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_194) begin
    if (ap_sig_bdd_194) begin
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_218) begin
    if (ap_sig_bdd_218) begin
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_247) begin
    if (ap_sig_bdd_247) begin
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st17_fsm_16 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_264) begin
    if (ap_sig_bdd_264) begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_17 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_279) begin
    if (ap_sig_bdd_279) begin
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st19_fsm_18 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_291) begin
    if (ap_sig_bdd_291) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_370) begin
    if (ap_sig_bdd_370) begin
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st20_fsm_19 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_451) begin
    if (ap_sig_bdd_451) begin
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st21_fsm_20 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_461) begin
    if (ap_sig_bdd_461) begin
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st22_fsm_21 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_470) begin
    if (ap_sig_bdd_470) begin
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st23_fsm_22 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_76) begin
    if (ap_sig_bdd_76) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_321) begin
    if (ap_sig_bdd_321) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_110) begin
    if (ap_sig_bdd_110) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_119) begin
    if (ap_sig_bdd_119) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_130) begin
    if (ap_sig_bdd_130) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_299) begin
    if (ap_sig_bdd_299) begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_138) begin
    if (ap_sig_bdd_138) begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_147) begin
    if (ap_sig_bdd_147) begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st2_fsm_1 or exitcond1_fu_620_p2 or ap_sig_bdd_84) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_620_p2 == ap_const_lv1_0) & ~ap_sig_bdd_84)) begin
        input_V_V_read = ap_const_logic_1;
    end else begin
        input_V_V_read = ap_const_logic_0;
    end
end

always @ (output_V_V_full_n or ap_sig_cseq_ST_st15_fsm_14 or tmp_28_fu_989_p2 or ap_sig_bdd_200 or ap_sig_cseq_ST_st21_fsm_20 or ap_sig_cseq_ST_st22_fsm_21 or ap_sig_cseq_ST_st23_fsm_22 or tmp_V_fu_1074_p5 or tmp_V_1_fu_1618_p5 or tmp_V_2_fu_1665_p5 or tmp_V_3_fu_1712_p5) begin
    if ((~(output_V_V_full_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st23_fsm_22))) begin
        output_V_V_din = tmp_V_3_fu_1712_p5;
    end else if ((~(output_V_V_full_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st22_fsm_21))) begin
        output_V_V_din = tmp_V_2_fu_1665_p5;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_20) & ~(output_V_V_full_n == ap_const_logic_0))) begin
        output_V_V_din = tmp_V_1_fu_1618_p5;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == tmp_28_fu_989_p2) & ~ap_sig_bdd_200)) begin
        output_V_V_din = tmp_V_fu_1074_p5;
    end else begin
        output_V_V_din = 'bx;
    end
end

always @ (output_V_V_full_n or ap_sig_cseq_ST_st15_fsm_14 or tmp_28_fu_989_p2 or ap_sig_bdd_200 or ap_sig_cseq_ST_st21_fsm_20 or ap_sig_cseq_ST_st22_fsm_21 or ap_sig_cseq_ST_st23_fsm_22) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == tmp_28_fu_989_p2) & ~ap_sig_bdd_200) | ((ap_const_logic_1 == ap_sig_cseq_ST_st21_fsm_20) & ~(output_V_V_full_n == ap_const_logic_0)) | (~(output_V_V_full_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st22_fsm_21)) | (~(output_V_V_full_n == ap_const_logic_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st23_fsm_22)))) begin
        output_V_V_write = ap_const_logic_1;
    end else begin
        output_V_V_write = ap_const_logic_0;
    end
end

always @ (tmp_47_cast_fu_1283_p1 or icmp4_fu_1129_p2 or tmp_46_fu_1175_p2 or tmp_51_cast_fu_1224_p1 or ap_sig_bdd_1229 or ap_sig_bdd_1231 or ap_sig_bdd_397) begin
    if (ap_sig_bdd_397) begin
        if (ap_sig_bdd_1231) begin
            storemerge1182_in_phi_fu_550_p6 = tmp_51_cast_fu_1224_p1;
        end else if (ap_sig_bdd_1229) begin
            storemerge1182_in_phi_fu_550_p6 = tmp_46_fu_1175_p2;
        end else if (~(ap_const_lv1_0 == icmp4_fu_1129_p2)) begin
            storemerge1182_in_phi_fu_550_p6 = tmp_47_cast_fu_1283_p1;
        end else begin
            storemerge1182_in_phi_fu_550_p6 = 'bx;
        end
    end else begin
        storemerge1182_in_phi_fu_550_p6 = 'bx;
    end
end

always @ (icmp3_fu_1113_p2 or r_V_15_fu_1288_p1 or tmp_58_fu_1323_p1 or ap_sig_bdd_225) begin
    if (ap_sig_bdd_225) begin
        if (~(ap_const_lv1_0 == icmp3_fu_1113_p2)) begin
            storemerge2_phi_fu_561_p4 = tmp_58_fu_1323_p1;
        end else if ((ap_const_lv1_0 == icmp3_fu_1113_p2)) begin
            storemerge2_phi_fu_561_p4 = r_V_15_fu_1288_p1;
        end else begin
            storemerge2_phi_fu_561_p4 = 'bx;
        end
    end else begin
        storemerge2_phi_fu_561_p4 = 'bx;
    end
end
always @ (output_V_V_full_n or ap_CS_fsm or exitcond1_fu_620_p2 or ap_sig_bdd_84 or icmp2_fu_753_p2 or tmp_10_fu_823_p2 or tmp_28_fu_989_p2 or ap_sig_bdd_200 or exitcond_fu_1091_p2 or tmp_29_fu_777_p2 or icmp1_fu_728_p2 or exitcond2_fu_801_p2) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((~ap_sig_bdd_84 & ~(exitcond1_fu_620_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end else if (((exitcond1_fu_620_p2 == ap_const_lv1_0) & ~ap_sig_bdd_84)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            if (~(ap_const_lv1_0 == icmp1_fu_728_p2)) begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        ap_ST_st4_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : 
        begin
            if (~(ap_const_lv1_0 == icmp2_fu_753_p2)) begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end
        end
        ap_ST_st6_fsm_5 : 
        begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : 
        begin
            if ((ap_const_lv1_0 == tmp_29_fu_777_p2)) begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st8_fsm_7 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        ap_ST_st9_fsm_8 : 
        begin
            if (~(ap_const_lv1_0 == exitcond2_fu_801_p2)) begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end else begin
                ap_NS_fsm = ap_ST_st9_fsm_8;
            end
        end
        ap_ST_st10_fsm_9 : 
        begin
            if (~(ap_const_lv1_0 == tmp_10_fu_823_p2)) begin
                ap_NS_fsm = ap_ST_st10_fsm_9;
            end else begin
                ap_NS_fsm = ap_ST_st11_fsm_10;
            end
        end
        ap_ST_st11_fsm_10 : 
        begin
            ap_NS_fsm = ap_ST_st12_fsm_11;
        end
        ap_ST_st12_fsm_11 : 
        begin
            ap_NS_fsm = ap_ST_st13_fsm_12;
        end
        ap_ST_st13_fsm_12 : 
        begin
            ap_NS_fsm = ap_ST_st14_fsm_13;
        end
        ap_ST_st14_fsm_13 : 
        begin
            ap_NS_fsm = ap_ST_st15_fsm_14;
        end
        ap_ST_st15_fsm_14 : 
        begin
            if ((~ap_sig_bdd_200 & ~(ap_const_lv1_0 == tmp_28_fu_989_p2))) begin
                ap_NS_fsm = ap_ST_st16_fsm_15;
            end else if (((ap_const_lv1_0 == tmp_28_fu_989_p2) & ~ap_sig_bdd_200)) begin
                ap_NS_fsm = ap_ST_st21_fsm_20;
            end else begin
                ap_NS_fsm = ap_ST_st15_fsm_14;
            end
        end
        ap_ST_st16_fsm_15 : 
        begin
            if (~(ap_const_lv1_0 == exitcond_fu_1091_p2)) begin
                ap_NS_fsm = ap_ST_st15_fsm_14;
            end else begin
                ap_NS_fsm = ap_ST_st17_fsm_16;
            end
        end
        ap_ST_st17_fsm_16 : 
        begin
            ap_NS_fsm = ap_ST_st18_fsm_17;
        end
        ap_ST_st18_fsm_17 : 
        begin
            ap_NS_fsm = ap_ST_st19_fsm_18;
        end
        ap_ST_st19_fsm_18 : 
        begin
            ap_NS_fsm = ap_ST_st20_fsm_19;
        end
        ap_ST_st20_fsm_19 : 
        begin
            ap_NS_fsm = ap_ST_st16_fsm_15;
        end
        ap_ST_st21_fsm_20 : 
        begin
            if (~(output_V_V_full_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st22_fsm_21;
            end else begin
                ap_NS_fsm = ap_ST_st21_fsm_20;
            end
        end
        ap_ST_st22_fsm_21 : 
        begin
            if (~(output_V_V_full_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st23_fsm_22;
            end else begin
                ap_NS_fsm = ap_ST_st22_fsm_21;
            end
        end
        ap_ST_st23_fsm_22 : 
        begin
            if (~(output_V_V_full_n == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st23_fsm_22;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


assign addr1_fu_1473_p3 = {{ap_const_lv57_3}, {t_V_6_reg_535}};

assign addr_cast_fu_1348_p1 = addr_fu_1342_p2;

assign addr_fu_1342_p2 = ($signed(ap_const_lv9_140) + $signed(tmp_47_cast1_fu_1338_p1));


always @ (ap_CS_fsm) begin
    ap_sig_bdd_110 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_119 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end


always @ (icmp3_fu_1113_p2 or icmp4_fu_1129_p2 or tmp_43_fu_1135_p2) begin
    ap_sig_bdd_1220 = ((ap_const_lv1_0 == icmp3_fu_1113_p2) & (ap_const_lv1_0 == icmp4_fu_1129_p2) & (ap_const_lv1_0 == tmp_43_fu_1135_p2));
end


always @ (icmp3_fu_1113_p2 or icmp4_fu_1129_p2 or tmp_43_fu_1135_p2) begin
    ap_sig_bdd_1222 = ((ap_const_lv1_0 == icmp3_fu_1113_p2) & (ap_const_lv1_0 == icmp4_fu_1129_p2) & ~(ap_const_lv1_0 == tmp_43_fu_1135_p2));
end


always @ (icmp3_fu_1113_p2 or icmp4_fu_1129_p2) begin
    ap_sig_bdd_1224 = ((ap_const_lv1_0 == icmp3_fu_1113_p2) & ~(ap_const_lv1_0 == icmp4_fu_1129_p2));
end


always @ (icmp4_fu_1129_p2 or tmp_43_fu_1135_p2) begin
    ap_sig_bdd_1229 = ((ap_const_lv1_0 == icmp4_fu_1129_p2) & (ap_const_lv1_0 == tmp_43_fu_1135_p2));
end


always @ (icmp4_fu_1129_p2 or tmp_43_fu_1135_p2) begin
    ap_sig_bdd_1231 = ((ap_const_lv1_0 == icmp4_fu_1129_p2) & ~(ap_const_lv1_0 == tmp_43_fu_1135_p2));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_130 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_138 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_7]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_147 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_8]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_156 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_9]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_176 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_B]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_185 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_C]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_194 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_E]);
end


always @ (output_V_V_full_n or tmp_28_fu_989_p2) begin
    ap_sig_bdd_200 = ((output_V_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == tmp_28_fu_989_p2));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_218 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_F]);
end


always @ (ap_sig_cseq_ST_st16_fsm_15 or exitcond_fu_1091_p2) begin
    ap_sig_bdd_225 = ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == exitcond_fu_1091_p2));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_247 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_10]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_264 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_11]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_279 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_12]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_291 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_0]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_299 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_321 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_349 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_D]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_370 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_13]);
end


always @ (ap_sig_cseq_ST_st16_fsm_15 or exitcond_fu_1091_p2 or icmp3_fu_1113_p2) begin
    ap_sig_bdd_397 = ((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & (ap_const_lv1_0 == exitcond_fu_1091_p2) & (ap_const_lv1_0 == icmp3_fu_1113_p2));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_425 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_A]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_451 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_14]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_461 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_15]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_470 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_16]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_76 = (ap_CS_fsm[ap_const_lv32_1] == ap_const_lv1_1);
end


always @ (input_V_V_empty_n or exitcond1_fu_620_p2) begin
    ap_sig_bdd_84 = ((input_V_V_empty_n == ap_const_logic_0) & (exitcond1_fu_620_p2 == ap_const_lv1_0));
end


always @ (ap_sig_cseq_ST_st2_fsm_1 or exitcond1_fu_620_p2 or ap_sig_bdd_84) begin
    ap_sig_bdd_90 = ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond1_fu_620_p2 == ap_const_lv1_0) & ~ap_sig_bdd_84);
end

assign exitcond1_fu_620_p2 = (i_reg_409 == ap_const_lv5_10? 1'b1: 1'b0);

assign exitcond2_fu_801_p2 = (tmp_20_fu_797_p1 == ap_const_lv6_37? 1'b1: 1'b0);

assign exitcond_fu_1091_p2 = (t_V_6_reg_535 == ap_const_lv7_40? 1'b1: 1'b0);

assign grp_fu_571_p2 = (initial_length_V + ap_const_lv32_1);

assign grp_fu_583_p4 = {{tmp_V_4_reg_1734[ap_const_lv32_17 : ap_const_lv32_10]}};

assign grp_fu_596_p2 = (d_V ^ ap_const_lv32_FFFFFFFF);

assign i_1_fu_626_p2 = (i_reg_409 + ap_const_lv5_1);

assign i_V_fu_1097_p2 = (t_V_6_reg_535 + ap_const_lv7_1);

assign icmp1_fu_728_p2 = (grp_fu_583_p4 == ap_const_lv8_0? 1'b1: 1'b0);

assign icmp2_fu_753_p2 = (tmp_40_fu_744_p4 == ap_const_lv8_0? 1'b1: 1'b0);

assign icmp3_fu_1113_p2 = (tmp_57_fu_1103_p4 == ap_const_lv3_0? 1'b1: 1'b0);

assign icmp4_fu_1129_p2 = (tmp_59_fu_1119_p4 == ap_const_lv2_0? 1'b1: 1'b0);

assign icmp_fu_646_p2 = (tmp_16_fu_636_p4 == ap_const_lv8_0? 1'b1: 1'b0);

assign lhs_V_14_cast_fu_1430_p1 = tmp_49_reg_1891;

assign lhs_V_1_cast_fu_854_p1 = t_V_2_reg_1755;

assign lhs_V_2_cast_fu_955_p1 = tmp_19_reg_1835;

assign lhs_V_6_fu_1299_p2 = (b_V ^ ap_const_lv32_FFFFFFFF);

assign p_0107_0_i1_fu_841_p3 = {{tmp_39_fu_837_p1}, {ap_const_lv3_0}};

assign p_0107_0_i1_trunc_fu_849_p1 = p_0107_0_i1_fu_841_p3;

assign p_0107_0_i_trunc_fu_951_p1 = tmp_30_reg_1830;

assign p_10_fu_1692_p4 = {{lhs_V_4_reg_476[ap_const_lv32_F : ap_const_lv32_8]}};

assign p_11_fu_1702_p4 = {{lhs_V_4_reg_476[ap_const_lv32_17 : ap_const_lv32_10]}};

assign p_1_fu_1054_p4 = {{lhs_V_1_reg_512[ap_const_lv32_F : ap_const_lv32_8]}};

assign p_2_fu_1064_p4 = {{lhs_V_1_reg_512[ap_const_lv32_17 : ap_const_lv32_10]}};

assign p_3_fu_1044_p4 = {{lhs_V_1_reg_512[ap_const_lv32_1F : ap_const_lv32_18]}};

assign p_4_fu_1588_p4 = {{lhs_V_2_reg_500[ap_const_lv32_1F : ap_const_lv32_18]}};

assign p_5_fu_1598_p4 = {{lhs_V_2_reg_500[ap_const_lv32_F : ap_const_lv32_8]}};

assign p_6_fu_1608_p4 = {{lhs_V_2_reg_500[ap_const_lv32_17 : ap_const_lv32_10]}};

assign p_7_fu_1682_p4 = {{lhs_V_4_reg_476[ap_const_lv32_1F : ap_const_lv32_18]}};

assign p_8_fu_1635_p4 = {{lhs_V_3_reg_488[ap_const_lv32_1F : ap_const_lv32_18]}};

assign p_9_fu_1645_p4 = {{lhs_V_3_reg_488[ap_const_lv32_F : ap_const_lv32_8]}};

assign p_s_fu_1655_p4 = {{lhs_V_3_reg_488[ap_const_lv32_17 : ap_const_lv32_10]}};

assign p_shl1_fu_1204_p3 = {{tmp_62_fu_1200_p1}, {ap_const_lv2_0}};

assign p_shl2_fu_1167_p3 = {{tmp_63_fu_1163_p1}, {ap_const_lv3_0}};

assign p_shl_cast_fu_1263_p1 = tmp_61_fu_1257_p2;

assign phitmp148_i_trunc_fu_923_p1 = phitmp148_i_reg_1820;

assign phitmp149_i_trunc_fu_937_p1 = phitmp149_i_reg_1825;

assign phitmp1_fu_657_p4 = {{input_V_V_dout[ap_const_lv32_1F : ap_const_lv32_18]}};

assign phitmp1_trunc_fu_667_p1 = phitmp1_fu_657_p4;

assign phitmp2_trunc_fu_739_p1 = grp_fu_583_p4;

assign phitmp_i_fu_868_p4 = {{initial_length_V_load_reg_395[ap_const_lv32_C : ap_const_lv32_5]}};

assign phitmp_i_trunc_fu_878_p1 = phitmp_i_fu_868_p4;

assign phitmp_trunc_fu_773_p1 = phitmp_reg_1780;

assign r_V_11_fu_1241_p2 = (r_V_27_fu_1235_p2 | r_V_26_fu_1229_p2);

assign r_V_12_fu_1188_p2 = (tmp2_fu_1182_p2 ^ c_V);

assign r_V_14_fu_1147_p2 = (c_V ^ r_V_28_fu_1141_p2);

assign r_V_15_fu_1288_p1 = storemerge1182_in_phi_fu_550_p6[3:0];

assign r_V_16_fu_1433_p2 = (ap_const_lv33_1 + lhs_V_14_cast_fu_1430_p1);

assign r_V_17_fu_1444_p2 = (ap_const_lv33_2 + lhs_V_14_cast_fu_1430_p1);

assign r_V_18_fu_1463_p2 = (ap_const_lv33_3 + lhs_V_14_cast_reg_1936);

assign r_V_19_fu_1490_p5 = {{{{tmp_68_fu_1486_p1}, {tmp_67_reg_1956}}, {tmp_66_reg_1951}}, {tmp_65_reg_1931}};

assign r_V_1_fu_913_p2 = (ap_const_lv33_2 + lhs_V_1_cast_reg_1814);

assign r_V_23_fu_1560_p2 = (r_V_31_fu_1555_p2 | r_V_29_fu_1547_p2);

assign r_V_24_fu_1293_p2 = (c_V & b_V);

assign r_V_25_fu_1305_p2 = (d_V & lhs_V_6_fu_1299_p2);

assign r_V_26_fu_1229_p2 = (b_V & d_V);

assign r_V_27_fu_1235_p2 = (c_V & grp_fu_596_p2);

assign r_V_28_fu_1141_p2 = (b_V | grp_fu_596_p2);

assign r_V_29_fu_1547_p2 = this_assign_1_reg_1971 << this_assign_2_fu_1544_p1;

assign r_V_2_fu_927_p2 = (ap_const_lv33_3 + lhs_V_1_cast_reg_1814);

assign r_V_30_fu_1520_p2 = (ap_const_lv5_0 - tmp_69_fu_1516_p1);

assign r_V_31_fu_1555_p2 = this_assign_1_reg_1971 >> tmp_40_i_cast_fu_1552_p1;

assign r_V_3_fu_958_p2 = (ap_const_lv33_1 + lhs_V_2_cast_fu_955_p1);

assign r_V_4_fu_969_p2 = (ap_const_lv33_2 + lhs_V_2_cast_reg_1840);

assign r_V_5_fu_979_p2 = (ap_const_lv33_3 + lhs_V_2_cast_reg_1840);

assign r_V_8_fu_1311_p2 = (r_V_25_fu_1305_p2 | r_V_24_fu_1293_p2);

assign r_V_fu_857_p2 = (ap_const_lv33_1 + lhs_V_1_cast_fu_854_p1);

assign rhs_V_13_cast8_trunc_fu_787_p1 = tmp_11_reg_1741;

assign t_V_1_fu_791_p2 = (ap_const_lv32_1 + storemerge_in_reg_456);

assign t_V_2_fu_716_p2 = (tmp_3_fu_712_p1 + tmp_1_fu_696_p2);

assign t_V_3_fu_817_p2 = (storemerge1179_in_reg_466 + ap_const_lv32_1);

assign t_V_6_cast_fu_1087_p1 = t_V_6_reg_535;

assign this_assign_1_fu_1510_p2 = (tmp5_fu_1504_p2 + tmp4_fu_1499_p2);

assign this_assign_2_fu_1544_p1 = tmp_69_reg_1977;

assign tmp1_cast_fu_1273_p1 = tmp1_fu_1267_p2;

assign tmp1_fu_1267_p2 = (ap_const_lv6_1 + tmp_60_fu_1253_p1);

assign tmp2_fu_1182_p2 = (b_V ^ d_V);

assign tmp4_fu_1499_p2 = (a_V + BLA_load_reg_1926);

assign tmp5_fu_1504_p2 = (f_V + r_V_19_fu_1490_p5);

assign tmp_10_fu_823_p2 = (t_V_3_fu_817_p2 < t_V_2_reg_1755? 1'b1: 1'b0);

assign tmp_11_fu_632_p1 = input_V_V_dout[7:0];

assign tmp_13_fu_828_p1 = t_V_3_fu_817_p2;

assign tmp_14_fu_833_p1 = t_V_2_reg_1755;

assign tmp_15_fu_863_p1 = r_V_fu_857_p2;

assign tmp_16_fu_636_p4 = {{input_V_V_dout[ap_const_lv32_1F : ap_const_lv32_18]}};

assign tmp_17_fu_918_p1 = r_V_1_fu_913_p2;

assign tmp_18_fu_932_p1 = r_V_2_fu_927_p2;

assign tmp_19_fu_941_p2 = (ap_const_lv32_5 + tmp_6_reg_1764);

assign tmp_1_fu_696_p2 = (ap_const_lv32_1 + initial_length_V_load_reg_395);

assign tmp_20_fu_797_p1 = storemerge_in_reg_456[5:0];

assign tmp_21_fu_946_p1 = tmp_19_fu_941_p2;

assign tmp_22_fu_964_p1 = r_V_3_fu_958_p2;

assign tmp_23_fu_974_p1 = r_V_4_fu_969_p2;

assign tmp_24_fu_984_p1 = r_V_5_fu_979_p2;

assign tmp_25_fu_768_p1 = initial_length_V;

assign tmp_28_fu_989_p2 = (storemerge_reg_523 < t_V_2_reg_1755? 1'b1: 1'b0);

assign tmp_29_fu_777_p2 = (tmp_11_reg_1741 == ap_const_lv8_0? 1'b1: 1'b0);

assign tmp_2_fu_652_p1 = initial_length_V;

assign tmp_32_fu_782_p1 = initial_length_V;

assign tmp_34_fu_1376_p2 = (h0_V_load_reg_1849 + a_V);

assign tmp_35_fu_1387_p2 = (h1_V_load_reg_1854 + b_V);

assign tmp_36_fu_1398_p2 = (h2_V_load_reg_1859 + c_V);

assign tmp_37_fu_1409_p2 = (h3_V_load_reg_1864 + d_V);

assign tmp_38_fu_1420_p2 = (storemerge_reg_523 + ap_const_lv32_40);

assign tmp_39_fu_837_p1 = initial_length_V_load_reg_395[4:0];

assign tmp_3_fu_712_p1 = tmp_9_fu_706_p2;

assign tmp_40_fu_744_p4 = {{tmp_V_4_reg_1734[ap_const_lv32_F : ap_const_lv32_8]}};

assign tmp_40_i_cast_fu_1552_p1 = r_V_30_reg_1982;

assign tmp_41_fu_1040_p1 = lhs_V_1_reg_512[7:0];

assign tmp_42_fu_1277_p2 = (tmp1_cast_fu_1273_p1 + p_shl_cast_fu_1263_p1);

assign tmp_43_fu_1135_p2 = (t_V_6_reg_535 < ap_const_lv7_30? 1'b1: 1'b0);

assign tmp_44_fu_1212_p2 = (p_shl1_fu_1204_p3 - t_V_6_cast_fu_1087_p1);

assign tmp_45_fu_1218_p2 = (ap_const_lv8_5 + tmp_44_fu_1212_p2);

assign tmp_46_fu_1175_p2 = (p_shl2_fu_1167_p3 - tmp_52_cast_fu_1159_p1);

assign tmp_47_cast1_fu_1338_p1 = t_V_6_reg_535;

assign tmp_47_cast_fu_1283_p1 = tmp_42_fu_1277_p2;

assign tmp_47_fu_1584_p1 = lhs_V_2_reg_500[7:0];

assign tmp_48_fu_1353_p4 = {{storemerge_reg_523[ap_const_lv32_1F : ap_const_lv32_4]}};

assign tmp_49_fu_1363_p3 = {{tmp_48_fu_1353_p4}, {storemerge2_phi_fu_561_p4}};

assign tmp_50_fu_1371_p1 = tmp_49_fu_1363_p3;

assign tmp_51_cast_fu_1224_p1 = tmp_45_fu_1218_p2;

assign tmp_51_fu_1439_p1 = r_V_16_fu_1433_p2;

assign tmp_52_cast_fu_1159_p1 = t_V_6_reg_535;

assign tmp_52_fu_1450_p1 = r_V_17_fu_1444_p2;

assign tmp_53_fu_1468_p1 = r_V_18_fu_1463_p2;

assign tmp_54_fu_1566_p2 = (b_V + r_V_23_fu_1560_p2);

assign tmp_55_fu_1631_p1 = lhs_V_3_reg_488[7:0];

assign tmp_56_fu_1678_p1 = lhs_V_4_reg_476[7:0];

assign tmp_57_fu_1103_p4 = {{t_V_6_reg_535[ap_const_lv32_6 : ap_const_lv32_4]}};

assign tmp_58_fu_1323_p1 = t_V_6_reg_535[3:0];

assign tmp_59_fu_1119_p4 = {{t_V_6_reg_535[ap_const_lv32_6 : ap_const_lv32_5]}};

assign tmp_60_fu_1253_p1 = t_V_6_reg_535[5:0];

assign tmp_61_fu_1257_p2 = t_V_6_reg_535 << ap_const_lv7_2;

assign tmp_62_fu_1200_p1 = t_V_6_reg_535[5:0];

assign tmp_63_fu_1163_p1 = t_V_6_reg_535[5:0];

assign tmp_65_fu_1426_p1 = BLA_q0[7:0];

assign tmp_66_fu_1455_p1 = BLA_q1[7:0];

assign tmp_67_fu_1459_p1 = BLA_q0[7:0];

assign tmp_68_fu_1486_p1 = BLA_q1[7:0];

assign tmp_69_fu_1516_p1 = BLA_q0[4:0];

assign tmp_6_fu_722_p2 = (tmp_3_fu_712_p1 + initial_length_V_load_reg_395);

assign tmp_7_fu_812_p1 = initial_length_V_load_reg_395;

assign tmp_8_fu_734_p1 = initial_length_V;

assign tmp_9_fu_706_p2 = ($signed(ap_const_lv6_38) - $signed(tmp_fu_702_p1));

assign tmp_V_1_fu_1618_p5 = {{{{tmp_47_fu_1584_p1}, {p_5_fu_1598_p4}}, {p_6_fu_1608_p4}}, {p_4_fu_1588_p4}};

assign tmp_V_2_fu_1665_p5 = {{{{tmp_55_fu_1631_p1}, {p_9_fu_1645_p4}}, {p_s_fu_1655_p4}}, {p_8_fu_1635_p4}};

assign tmp_V_3_fu_1712_p5 = {{{{tmp_56_fu_1678_p1}, {p_10_fu_1692_p4}}, {p_11_fu_1702_p4}}, {p_7_fu_1682_p4}};

assign tmp_V_fu_1074_p5 = {{{{tmp_41_fu_1040_p1}, {p_1_fu_1054_p4}}, {p_2_fu_1064_p4}}, {p_3_fu_1044_p4}};

assign tmp_fu_702_p1 = tmp_1_fu_696_p2[5:0];
always @ (posedge ap_clk) begin
    lhs_V_1_cast_reg_1814[32] <= 1'b0;
    lhs_V_2_cast_reg_1840[32] <= 1'b0;
    lhs_V_14_cast_reg_1936[32] <= 1'b0;
end



endmodule //toplevel

